steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
  
  # Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
  
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

timeout: '1200s'